/* =====================================================================
   Diego Ignacio Fernandez Alarcon
   PRY2205 - CBD Semana 9 
   Base: Oracle XE local (XEPDB1)

   

   Usuarios:
   - SYSTEM           : administra usuarios/roles (Caso 1)
   - PRY2205_EFT      : owner (poblamiento, sinonimos publicos, Caso 3, indice)
   - PRY2205_EFT_DES  : desarrollador (Caso 2: VIEW CARTOLA_PROFESIONALES)
   - PRY2205_EFT_CON  : consumidor (consultas y evidencias de Caso 2 y Caso 3)

   ===================================================================== */


  ---
    -- CHECK 
   
   ---
SELECT USER AS usuario, SYS_CONTEXT('USERENV','CON_NAME') AS container FROM dual;


--- 
   -- PARTE 1 - CASO 1 (Seguridad: roles/usuarios/permisos)
   -- USUARIO: SYSTEM (conectado a XEPDB1)
   ---

-- 1.1) Limpieza 
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT_CON CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT_DES CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_C'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

--  Crear roles
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

--  Usuarios 
CREATE USER PRY2205_EFT
IDENTIFIED BY "Clave#Db2025AA11"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 50M ON USERS;

CREATE USER PRY2205_EFT_DES
IDENTIFIED BY "Clave#Db2025BB22"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 50M ON USERS;

CREATE USER PRY2205_EFT_CON
IDENTIFIED BY "Clave#Db2025CC33"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 50M ON USERS;

--  Privilegios base de sesion
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

--  Privilegios de desarrollo 
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT_DES;

--  Permitir crear sinonimos publicos (lo usara el owner para los SYN_*)
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;
GRANT DROP PUBLIC SYNONYM   TO PRY2205_EFT;

--  Asignacion de roles
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

--  Evidencia Caso 1 (SYSTEM)


SELECT username
FROM dba_users
WHERE username IN ('PRY2205_EFT','PRY2205_EFT_DES','PRY2205_EFT_CON')
ORDER BY username;

SELECT role
FROM dba_roles
WHERE role IN ('PRY2205_ROL_D','PRY2205_ROL_C')
ORDER BY role;

SELECT grantee, granted_role
FROM dba_role_privs
WHERE grantee IN ('PRY2205_EFT','PRY2205_EFT_DES','PRY2205_EFT_CON')
ORDER BY grantee, granted_role;





/* =====================================================================
   - PREPARACION DE ACCESO (Sinonimos publicos + grants base)
   USUARIO: PRY2205_EFT
   ===================================================================== */


BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_ASESORIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_EMPRESA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_PROFESIONAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_PROFESION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_TIPO_CONTRATO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_ISAPRE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_RANGOS_SUELDOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE PUBLIC SYNONYM SYN_ASESORIA       FOR PRY2205_EFT.ASESORIA;
CREATE PUBLIC SYNONYM SYN_EMPRESA        FOR PRY2205_EFT.EMPRESA;
CREATE PUBLIC SYNONYM SYN_PROFESIONAL    FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM SYN_PROFESION      FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM SYN_TIPO_CONTRATO  FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE PUBLIC SYNONYM SYN_ISAPRE         FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM SYN_RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;

--  Grants para roles (consultas)
GRANT SELECT ON EMPRESA        TO PRY2205_ROL_D;
GRANT SELECT ON ASESORIA       TO PRY2205_ROL_D;
GRANT SELECT ON PROFESIONAL    TO PRY2205_ROL_D;
GRANT SELECT ON PROFESION      TO PRY2205_ROL_D;
GRANT SELECT ON ISAPRE         TO PRY2205_ROL_D;
GRANT SELECT ON TIPO_CONTRATO  TO PRY2205_ROL_D;
GRANT SELECT ON RANGOS_SUELDOS TO PRY2205_ROL_D;
GRANT SELECT ON EMPRESA        TO PRY2205_ROL_C;
GRANT SELECT ON ASESORIA       TO PRY2205_ROL_C;

--  Grants DIRECTOS con GRANT OPTION a DES 
GRANT SELECT ON PROFESIONAL    TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON PROFESION      TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON ISAPRE         TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON TIPO_CONTRATO  TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON RANGOS_SUELDOS TO PRY2205_EFT_DES WITH GRANT OPTION;

--  Para EXPLAIN PLAN desde CON sobre vista de otro schema
GRANT SELECT ON EMPRESA  TO PRY2205_EFT_CON;
GRANT SELECT ON ASESORIA TO PRY2205_EFT_CON;

-- Evidencia (EFT): confirmar GRANTABLE = YES para DES

SELECT owner, table_name, privilege, grantee, grantable
FROM all_tab_privs
WHERE grantee = 'PRY2205_EFT_DES'
  AND owner   = 'PRY2205_EFT'
  AND table_name IN ('PROFESIONAL','PROFESION','ISAPRE','TIPO_CONTRATO','RANGOS_SUELDOS')
ORDER BY table_name;


/* =====================================================================
   CASO 2 (Informe CARTOLA) como VIEW
   USUARIO: PRY2205_EFT_DES
   ===================================================================== */

--  Drop si existe
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW CARTOLA_PROFESIONALES';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

--   VIEW CARTOLA_PROFESIONALES (columna PORCENTAJE_HONORARIO incluida)
CREATE OR REPLACE VIEW CARTOLA_PROFESIONALES AS
SELECT
  p.RUTPROF                                                   AS RUT_PROFESIONAL,
  INITCAP(p.NOMPRO || ' ' || p.APPPRO || ' ' || p.APMPRO)      AS NOMBRE_PROFESIONAL,
  INITCAP(pr.NOMPROFESION)                                     AS PROFESION,
  INITCAP(i.NOMISAPRE)                                         AS ISAPRE,
  p.SUELDO                                                     AS SUELDO_BASE,
  NVL(p.COMISION, 0)                                           AS PORC_COMISION_PROFESIONAL,
  ROUND(p.SUELDO * NVL(p.COMISION, 0), 0)                      AS VALOR_TOTAL_COMISION,
  ROUND(p.SUELDO * (rs.HONOR_PCT / 100), 0)                    AS PORCENTAJE_HONORARIO,
  NVL(tc.INCENTIVO, 0)                                        AS BONO_MOVILIZACION,
  ROUND(
    p.SUELDO
    + (p.SUELDO * NVL(p.COMISION, 0))
    + (p.SUELDO * (rs.HONOR_PCT / 100))
    + NVL(tc.INCENTIVO, 0)
  , 0)                                                        AS TOTAL_PAGAR
FROM SYN_PROFESIONAL p
JOIN SYN_PROFESION pr
  ON pr.IDPROFESION = p.IDPROFESION
JOIN SYN_ISAPRE i
  ON i.IDISAPRE = p.IDISAPRE
JOIN SYN_TIPO_CONTRATO tc
  ON tc.IDTCONTRATO = p.IDTCONTRATO
JOIN SYN_RANGOS_SUELDOS rs
  ON p.SUELDO BETWEEN rs.S_MIN AND rs.S_MAX
;

--  Permisos de la VIEW para consumidor (rol + directo)
GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_ROL_C;
GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_CON;

--  Evidencia caso 2 (DES)

SELECT COUNT(*) AS total_filas FROM CARTOLA_PROFESIONALES;
SELECT * FROM CARTOLA_PROFESIONALES FETCH FIRST 10 ROWS ONLY;


----
   ---sinonimo PUBLIC a la VIEW CARTOLA (para que CON consulte como SYN_CARTOLA_PROFESIONALES)
   ---USUARIO: PRY2205_EFT
   

BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_CARTOLA_PROFESIONALES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE PUBLIC SYNONYM SYN_CARTOLA_PROFESIONALES FOR PRY2205_EFT_DES.CARTOLA_PROFESIONALES;

-- Evidencia  sinonimo publico creado CARTOLA ---
 
SELECT owner, synonym_name, table_owner, table_name
FROM all_synonyms
WHERE synonym_name = 'SYN_CARTOLA_PROFESIONALES';



   --- - EVIDENCIA CASO 2 
   ---- USUARIO: PRY2205_EFT_CON
  


SELECT COUNT(*) AS total_filas FROM SYN_CARTOLA_PROFESIONALES;
SELECT * FROM SYN_CARTOLA_PROFESIONALES FETCH FIRST 10 ROWS ONLY;


--
    --CASO 3 (Vista   empresas asesoradas)
   ---USUARIO: PRY2205_EFT
  

-- 7.1) Drop si existe
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_EMPRESAS_ASESORADAS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

--- 7.2)  VIEW
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
  LPAD(TO_CHAR(e.rut_empresa), 8, '0') || '-' || LOWER(e.dv_empresa)      AS rut_empresa,
  INITCAP(e.nomempresa)                                                  AS nombre_empresa,
  TRUNC(MONTHS_BETWEEN(SYSDATE, e.fecha_iniciacion_actividades) / 12)     AS anios_existencia,
  e.iva_declarado                                                        AS iva,
  ROUND(COUNT(a.inicio) / 12, 0)                                          AS total_asesorias_anuales,
  ROUND(e.iva_declarado * ((COUNT(a.inicio) / 12) / 100), 0)              AS devolucion_iva,
  CASE
    WHEN (COUNT(a.inicio) / 12) > 5 THEN 'CLIENTE PREMIUM'
    WHEN (COUNT(a.inicio) / 12) BETWEEN 3 AND 5 THEN 'CLIENTE'
    ELSE 'CLIENTE POCO CONCURRIDO'
  END                                                                    AS tipo_cliente,
  CASE
    WHEN (COUNT(a.inicio) / 12) > 5 THEN
      CASE
        WHEN COUNT(a.inicio) >= 7 THEN '1 ASESORIA GRATIS'
        ELSE '1 ASESORIA 40% DE DESCUENTO'
      END
    WHEN (COUNT(a.inicio) / 12) BETWEEN 3 AND 5 THEN
      CASE
        WHEN COUNT(a.inicio) = 5 THEN '1 ASESORIA 30% DE DESCUENTO'
        ELSE '1 ASESORIA 20% DE DESCUENTO'
      END
    ELSE 'CAPTAR CLIENTE'
  END                                                                    AS corresponde
FROM empresa e
JOIN asesoria a ON a.idempresa = e.idempresa
WHERE
  a.fin >= TRUNC(ADD_MONTHS(SYSDATE, -12), 'YYYY')
  AND a.fin <  TRUNC(SYSDATE, 'YYYY')
GROUP BY
  e.rut_empresa,
  e.dv_empresa,
  e.nomempresa,
  e.fecha_iniciacion_actividades,
  e.iva_declarado
ORDER BY
  INITCAP(e.nomempresa) ASC
;

-- 7.3) Permisos
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_ROL_C;
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;

-- 7.4) Sinonimo publico
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_VW_EMPRESAS_ASESORADAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE PUBLIC SYNONYM SYN_VW_EMPRESAS_ASESORADAS FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

--EVIDENCIA CASO 3

SELECT COUNT(*) AS total_filas FROM VW_EMPRESAS_ASESORADAS;
SELECT * FROM VW_EMPRESAS_ASESORADAS FETCH FIRST 10 ROWS ONLY;


--  OPTIMIZACION: indice para ASESORIA(FIN, IDEMPRESA)

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_ASESORIA_FIN_IDEMPRESA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE INDEX IX_ASESORIA_FIN_IDEMPRESA
ON ASESORIA (FIN, IDEMPRESA);

-- Evidencia indice (EFT)

SELECT index_name, table_name
FROM user_indexes
WHERE index_name = 'IX_ASESORIA_FIN_IDEMPRESA';


-- ====================================================
   ---EVIDENCIA CASO 3 (Consumidor +  PLAN )
   ---USUARIO:         PRY2205_EFT_CON
  

--EVIDENCIA CASO 3 (CON) ===

-- Confirmar sinonimo publico
SELECT owner, synonym_name, table_owner, table_name
FROM all_synonyms
WHERE synonym_name = 'SYN_VW_EMPRESAS_ASESORADAS';

-- Datos
SELECT COUNT(*) AS total_filas FROM SYN_VW_EMPRESAS_ASESORADAS;
SELECT * FROM SYN_VW_EMPRESAS_ASESORADAS FETCH FIRST 10 ROWS ONLY;

-- Plan (INDEX RANGE SCAN IX_ASESORIA_FIN_IDEMPRESA)
EXPLAIN PLAN FOR
SELECT *
FROM SYN_VW_EMPRESAS_ASESORADAS;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);




